"""v1.1 etapa c: regras de alerta

Revision ID: 568c707880c2
Revises: ad58059ee96c
Create Date: 2026-09-04 11:53:26.562608
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '568c707880c2'
down_revision: str | None = 'ad58059ee96c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regras_alerta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('entidade', sa.String(length=20), nullable=False),
    sa.Column('indicador', sa.String(length=50), nullable=False),
    sa.Column('operador', sa.String(length=4), nullable=False),
    sa.Column('limite', sa.Float(), nullable=False),
    sa.Column('severidade', sa.String(length=20), nullable=False),
    sa.Column('escopo', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regras_alerta'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regras_alerta')
    # ### end Alembic commands ###
