"""v1.1 etapa b: composicao financeira (bruta glosa coparticipacao liquida)

Revision ID: ad58059ee96c
Revises: f16dee56465a
Create Date: 2026-09-04 11:33:16.281792
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ad58059ee96c'
down_revision: str | None = 'f16dee56465a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # agg_sinistralidade_competencia é 100% derivada (reconstruída pelo seed) — os
    # defaults abaixo só evitam erro de NOT NULL em linhas existentes até o rebuild.
    op.add_column('agg_sinistralidade_competencia', sa.Column('despesa_bruta', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('agg_sinistralidade_competencia', sa.Column('glosas', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('agg_sinistralidade_competencia', sa.Column('coparticipacao', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('agg_sinistralidade_competencia', sa.Column('despesa_liquida', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('agg_sinistralidade_competencia', sa.Column('sinistralidade_bruta', sa.Float(), nullable=False, server_default='0'))
    op.add_column('agg_sinistralidade_competencia', sa.Column('sinistralidade_liquida', sa.Float(), nullable=False, server_default='0'))
    op.drop_column('agg_sinistralidade_competencia', 'sinistralidade')
    op.drop_column('agg_sinistralidade_competencia', 'despesa')
    op.add_column('eventos_assistenciais', sa.Column('valor_coparticipacao', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    op.add_column('planos', sa.Column('tem_coparticipacao', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('planos', sa.Column('percentual_coparticipacao', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0'))
    for tabela, coluna in (
        ('agg_sinistralidade_competencia', 'despesa_bruta'),
        ('agg_sinistralidade_competencia', 'glosas'),
        ('agg_sinistralidade_competencia', 'coparticipacao'),
        ('agg_sinistralidade_competencia', 'despesa_liquida'),
        ('agg_sinistralidade_competencia', 'sinistralidade_bruta'),
        ('agg_sinistralidade_competencia', 'sinistralidade_liquida'),
        ('eventos_assistenciais', 'valor_coparticipacao'),
        ('planos', 'tem_coparticipacao'),
        ('planos', 'percentual_coparticipacao'),
    ):
        op.alter_column(tabela, coluna, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planos', 'percentual_coparticipacao')
    op.drop_column('planos', 'tem_coparticipacao')
    op.drop_column('eventos_assistenciais', 'valor_coparticipacao')
    op.add_column('agg_sinistralidade_competencia', sa.Column('despesa', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
    op.add_column('agg_sinistralidade_competencia', sa.Column('sinistralidade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('agg_sinistralidade_competencia', 'sinistralidade_liquida')
    op.drop_column('agg_sinistralidade_competencia', 'sinistralidade_bruta')
    op.drop_column('agg_sinistralidade_competencia', 'despesa_liquida')
    op.drop_column('agg_sinistralidade_competencia', 'coparticipacao')
    op.drop_column('agg_sinistralidade_competencia', 'glosas')
    op.drop_column('agg_sinistralidade_competencia', 'despesa_bruta')
    # ### end Alembic commands ###
