"""esquema inicial (fonte + camada analitica)

Revision ID: df2d100420f5
Revises: 
Create Date: 2026-09-02 20:07:32.273269
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'df2d100420f5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_competencia_dimensao',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('dimensao', sa.String(length=20), nullable=False),
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('rotulo', sa.String(length=160), nullable=False),
    sa.Column('despesa', sa.Float(), nullable=False),
    sa.Column('eventos', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('beneficiarios', sa.Integer(), nullable=False),
    sa.Column('custo_medio', sa.Float(), nullable=False),
    sa.Column('freq_por_mil', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agg_competencia_dimensao')),
    sa.UniqueConstraint('competencia', 'dimensao', 'chave', name='uq_aggdim_comp_dim_chave')
    )
    op.create_index(op.f('ix_agg_competencia_dimensao_competencia'), 'agg_competencia_dimensao', ['competencia'], unique=False)
    op.create_index(op.f('ix_agg_competencia_dimensao_dimensao'), 'agg_competencia_dimensao', ['dimensao'], unique=False)
    op.create_table('agg_sinistralidade_competencia',
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('receita', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('despesa', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sinistralidade', sa.Float(), nullable=False),
    sa.Column('beneficiarios_ativos', sa.Integer(), nullable=False),
    sa.Column('exposicao_beneficiario_mes', sa.Integer(), nullable=False),
    sa.Column('eventos', sa.Integer(), nullable=False),
    sa.Column('custo_pmpm', sa.Float(), nullable=False),
    sa.Column('receita_media_beneficiario', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('competencia', name=op.f('pk_agg_sinistralidade_competencia'))
    )
    op.create_table('cenarios_gabarito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('competencia_alvo', sa.Date(), nullable=True),
    sa.Column('dimensao', sa.String(length=20), nullable=True),
    sa.Column('chave_alvo', sa.String(length=60), nullable=True),
    sa.Column('rotulo_alvo', sa.String(length=160), nullable=True),
    sa.Column('efeito_esperado', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.String(length=600), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cenarios_gabarito')),
    sa.UniqueConstraint('codigo', name=op.f('uq_cenarios_gabarito_codigo'))
    )
    op.create_table('competencias',
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('mes_nome', sa.String(length=20), nullable=False),
    sa.Column('trimestre', sa.Integer(), nullable=False),
    sa.Column('is_inverno', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('competencia', name=op.f('pk_competencias'))
    )
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('grupo', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_especialidades')),
    sa.UniqueConstraint('codigo', name=op.f('uq_especialidades_codigo'))
    )
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('segmentacao', sa.String(length=30), nullable=False),
    sa.Column('ticket_medio_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planos')),
    sa.UniqueConstraint('codigo', name=op.f('uq_planos_codigo'))
    )
    op.create_table('regioes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('macrorregiao', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regioes'))
    )
    op.create_table('seed_manifest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('beneficiarios', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=False),
    sa.Column('escala_eventos', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('contagens', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seed_manifest'))
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_plano'], ['planos.id'], name=op.f('fk_contratos_id_plano_planos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contratos'))
    )
    op.create_index(op.f('ix_contratos_id_plano'), 'contratos', ['id_plano'], unique=False)
    op.create_table('diagnosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('id_especialidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_especialidade'], ['especialidades.id'], name=op.f('fk_diagnosticos_id_especialidade_especialidades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnosticos')),
    sa.UniqueConstraint('cid', name=op.f('uq_diagnosticos_cid'))
    )
    op.create_index(op.f('ix_diagnosticos_id_especialidade'), 'diagnosticos', ['id_especialidade'], unique=False)
    op.create_table('prestadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_ficticio', sa.String(length=100), nullable=False),
    sa.Column('tipo_prestador', sa.String(length=30), nullable=False),
    sa.Column('id_regiao', sa.Integer(), nullable=False),
    sa.Column('id_especialidade_principal', sa.Integer(), nullable=False),
    sa.Column('nivel_preco', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidade_principal'], ['especialidades.id'], name=op.f('fk_prestadores_id_especialidade_principal_especialidades')),
    sa.ForeignKeyConstraint(['id_regiao'], ['regioes.id'], name=op.f('fk_prestadores_id_regiao_regioes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prestadores'))
    )
    op.create_index(op.f('ix_prestadores_id_especialidade_principal'), 'prestadores', ['id_especialidade_principal'], unique=False)
    op.create_index(op.f('ix_prestadores_id_regiao'), 'prestadores', ['id_regiao'], unique=False)
    op.create_table('procedimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('id_especialidade', sa.Integer(), nullable=False),
    sa.Column('grupo_procedimento', sa.String(length=60), nullable=False),
    sa.Column('complexidade', sa.Integer(), nullable=False),
    sa.Column('custo_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_atendimento_tipico', sa.String(length=20), nullable=False),
    sa.Column('idade_min', sa.Integer(), nullable=False),
    sa.Column('idade_max', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidade'], ['especialidades.id'], name=op.f('fk_procedimentos_id_especialidade_especialidades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procedimentos')),
    sa.UniqueConstraint('codigo', name=op.f('uq_procedimentos_codigo'))
    )
    op.create_index(op.f('ix_procedimentos_id_especialidade'), 'procedimentos', ['id_especialidade'], unique=False)
    op.create_table('receitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('quantidade_beneficiarios', sa.Integer(), nullable=False),
    sa.Column('receita_contraprestacao', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_plano'], ['planos.id'], name=op.f('fk_receitas_id_plano_planos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receitas')),
    sa.UniqueConstraint('competencia', 'id_plano', name='uq_receita_comp_plano')
    )
    op.create_index(op.f('ix_receitas_competencia'), 'receitas', ['competencia'], unique=False)
    op.create_index(op.f('ix_receitas_id_plano'), 'receitas', ['id_plano'], unique=False)
    op.create_table('agg_prestador_competencia',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('id_prestador', sa.Integer(), nullable=False),
    sa.Column('despesa', sa.Float(), nullable=False),
    sa.Column('eventos', sa.Integer(), nullable=False),
    sa.Column('beneficiarios', sa.Integer(), nullable=False),
    sa.Column('custo_medio', sa.Float(), nullable=False),
    sa.Column('participacao', sa.Float(), nullable=False),
    sa.Column('procedimento_top_id', sa.Integer(), nullable=True),
    sa.Column('procedimento_top_share', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_prestador'], ['prestadores.id'], name=op.f('fk_agg_prestador_competencia_id_prestador_prestadores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agg_prestador_competencia')),
    sa.UniqueConstraint('competencia', 'id_prestador', name='uq_aggprest_comp_prest')
    )
    op.create_index(op.f('ix_agg_prestador_competencia_competencia'), 'agg_prestador_competencia', ['competencia'], unique=False)
    op.create_index(op.f('ix_agg_prestador_competencia_id_prestador'), 'agg_prestador_competencia', ['id_prestador'], unique=False)
    op.create_table('beneficiarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=16), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('faixa_etaria', sa.String(length=10), nullable=False),
    sa.Column('id_regiao', sa.Integer(), nullable=False),
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('id_contrato', sa.Integer(), nullable=False),
    sa.Column('data_adesao', sa.Date(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['id_contrato'], ['contratos.id'], name=op.f('fk_beneficiarios_id_contrato_contratos')),
    sa.ForeignKeyConstraint(['id_plano'], ['planos.id'], name=op.f('fk_beneficiarios_id_plano_planos')),
    sa.ForeignKeyConstraint(['id_regiao'], ['regioes.id'], name=op.f('fk_beneficiarios_id_regiao_regioes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beneficiarios'))
    )
    op.create_index(op.f('ix_beneficiarios_codigo'), 'beneficiarios', ['codigo'], unique=True)
    op.create_index(op.f('ix_beneficiarios_faixa_etaria'), 'beneficiarios', ['faixa_etaria'], unique=False)
    op.create_index(op.f('ix_beneficiarios_id_contrato'), 'beneficiarios', ['id_contrato'], unique=False)
    op.create_index(op.f('ix_beneficiarios_id_plano'), 'beneficiarios', ['id_plano'], unique=False)
    op.create_index(op.f('ix_beneficiarios_id_regiao'), 'beneficiarios', ['id_regiao'], unique=False)
    op.create_table('agg_beneficiario_competencia',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('id_beneficiario', sa.Integer(), nullable=False),
    sa.Column('despesa', sa.Float(), nullable=False),
    sa.Column('eventos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_beneficiario'], ['beneficiarios.id'], name=op.f('fk_agg_beneficiario_competencia_id_beneficiario_beneficiarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agg_beneficiario_competencia')),
    sa.UniqueConstraint('competencia', 'id_beneficiario', name='uq_aggben_comp_ben')
    )
    op.create_index(op.f('ix_agg_beneficiario_competencia_competencia'), 'agg_beneficiario_competencia', ['competencia'], unique=False)
    op.create_index(op.f('ix_agg_beneficiario_competencia_id_beneficiario'), 'agg_beneficiario_competencia', ['id_beneficiario'], unique=False)
    op.create_table('eventos_assistenciais',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_beneficiario', sa.Integer(), nullable=False),
    sa.Column('id_prestador', sa.Integer(), nullable=False),
    sa.Column('id_procedimento', sa.Integer(), nullable=False),
    sa.Column('id_especialidade', sa.Integer(), nullable=False),
    sa.Column('id_diagnostico', sa.Integer(), nullable=True),
    sa.Column('id_regiao', sa.Integer(), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('tipo_atendimento', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_apresentado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_glosado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cenario_tag', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['id_beneficiario'], ['beneficiarios.id'], name=op.f('fk_eventos_assistenciais_id_beneficiario_beneficiarios')),
    sa.ForeignKeyConstraint(['id_diagnostico'], ['diagnosticos.id'], name=op.f('fk_eventos_assistenciais_id_diagnostico_diagnosticos')),
    sa.ForeignKeyConstraint(['id_especialidade'], ['especialidades.id'], name=op.f('fk_eventos_assistenciais_id_especialidade_especialidades')),
    sa.ForeignKeyConstraint(['id_prestador'], ['prestadores.id'], name=op.f('fk_eventos_assistenciais_id_prestador_prestadores')),
    sa.ForeignKeyConstraint(['id_procedimento'], ['procedimentos.id'], name=op.f('fk_eventos_assistenciais_id_procedimento_procedimentos')),
    sa.ForeignKeyConstraint(['id_regiao'], ['regioes.id'], name=op.f('fk_eventos_assistenciais_id_regiao_regioes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eventos_assistenciais'))
    )
    op.create_index('ix_evento_comp_espec', 'eventos_assistenciais', ['competencia', 'id_especialidade'], unique=False)
    op.create_index('ix_evento_comp_prest', 'eventos_assistenciais', ['competencia', 'id_prestador'], unique=False)
    op.create_index('ix_evento_comp_proc', 'eventos_assistenciais', ['competencia', 'id_procedimento'], unique=False)
    op.create_index('ix_evento_comp_tipo', 'eventos_assistenciais', ['competencia', 'tipo_atendimento'], unique=False)
    op.create_index(op.f('ix_eventos_assistenciais_cenario_tag'), 'eventos_assistenciais', ['cenario_tag'], unique=False)
    op.create_index(op.f('ix_eventos_assistenciais_competencia'), 'eventos_assistenciais', ['competencia'], unique=False)
    op.create_index(op.f('ix_eventos_assistenciais_id_beneficiario'), 'eventos_assistenciais', ['id_beneficiario'], unique=False)
    op.create_index(op.f('ix_eventos_assistenciais_id_especialidade'), 'eventos_assistenciais', ['id_especialidade'], unique=False)
    op.create_index(op.f('ix_eventos_assistenciais_id_prestador'), 'eventos_assistenciais', ['id_prestador'], unique=False)
    op.create_index(op.f('ix_eventos_assistenciais_id_procedimento'), 'eventos_assistenciais', ['id_procedimento'], unique=False)
    op.create_index(op.f('ix_eventos_assistenciais_id_regiao'), 'eventos_assistenciais', ['id_regiao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_assistenciais_id_regiao'), table_name='eventos_assistenciais')
    op.drop_index(op.f('ix_eventos_assistenciais_id_procedimento'), table_name='eventos_assistenciais')
    op.drop_index(op.f('ix_eventos_assistenciais_id_prestador'), table_name='eventos_assistenciais')
    op.drop_index(op.f('ix_eventos_assistenciais_id_especialidade'), table_name='eventos_assistenciais')
    op.drop_index(op.f('ix_eventos_assistenciais_id_beneficiario'), table_name='eventos_assistenciais')
    op.drop_index(op.f('ix_eventos_assistenciais_competencia'), table_name='eventos_assistenciais')
    op.drop_index(op.f('ix_eventos_assistenciais_cenario_tag'), table_name='eventos_assistenciais')
    op.drop_index('ix_evento_comp_tipo', table_name='eventos_assistenciais')
    op.drop_index('ix_evento_comp_proc', table_name='eventos_assistenciais')
    op.drop_index('ix_evento_comp_prest', table_name='eventos_assistenciais')
    op.drop_index('ix_evento_comp_espec', table_name='eventos_assistenciais')
    op.drop_table('eventos_assistenciais')
    op.drop_index(op.f('ix_agg_beneficiario_competencia_id_beneficiario'), table_name='agg_beneficiario_competencia')
    op.drop_index(op.f('ix_agg_beneficiario_competencia_competencia'), table_name='agg_beneficiario_competencia')
    op.drop_table('agg_beneficiario_competencia')
    op.drop_index(op.f('ix_beneficiarios_id_regiao'), table_name='beneficiarios')
    op.drop_index(op.f('ix_beneficiarios_id_plano'), table_name='beneficiarios')
    op.drop_index(op.f('ix_beneficiarios_id_contrato'), table_name='beneficiarios')
    op.drop_index(op.f('ix_beneficiarios_faixa_etaria'), table_name='beneficiarios')
    op.drop_index(op.f('ix_beneficiarios_codigo'), table_name='beneficiarios')
    op.drop_table('beneficiarios')
    op.drop_index(op.f('ix_agg_prestador_competencia_id_prestador'), table_name='agg_prestador_competencia')
    op.drop_index(op.f('ix_agg_prestador_competencia_competencia'), table_name='agg_prestador_competencia')
    op.drop_table('agg_prestador_competencia')
    op.drop_index(op.f('ix_receitas_id_plano'), table_name='receitas')
    op.drop_index(op.f('ix_receitas_competencia'), table_name='receitas')
    op.drop_table('receitas')
    op.drop_index(op.f('ix_procedimentos_id_especialidade'), table_name='procedimentos')
    op.drop_table('procedimentos')
    op.drop_index(op.f('ix_prestadores_id_regiao'), table_name='prestadores')
    op.drop_index(op.f('ix_prestadores_id_especialidade_principal'), table_name='prestadores')
    op.drop_table('prestadores')
    op.drop_index(op.f('ix_diagnosticos_id_especialidade'), table_name='diagnosticos')
    op.drop_table('diagnosticos')
    op.drop_index(op.f('ix_contratos_id_plano'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_table('seed_manifest')
    op.drop_table('regioes')
    op.drop_table('planos')
    op.drop_table('especialidades')
    op.drop_table('competencias')
    op.drop_table('cenarios_gabarito')
    op.drop_table('agg_sinistralidade_competencia')
    op.drop_index(op.f('ix_agg_competencia_dimensao_dimensao'), table_name='agg_competencia_dimensao')
    op.drop_index(op.f('ix_agg_competencia_dimensao_competencia'), table_name='agg_competencia_dimensao')
    op.drop_table('agg_competencia_dimensao')
    # ### end Alembic commands ###
