"""v1.1 etapa a: perfil de utilizacao do procedimento

Revision ID: f16dee56465a
Revises: df2d100420f5
Create Date: 2026-09-04 11:17:55.532598
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f16dee56465a'
down_revision: str | None = 'df2d100420f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default só para popular as linhas existentes; o seed reescreve com o
    # mapeamento correto por grupo_procedimento (GRUPO_PERFIL_UTILIZACAO).
    op.add_column(
        'procedimentos',
        sa.Column('perfil_utilizacao', sa.String(length=12), nullable=False, server_default='variavel'),
    )
    op.alter_column('procedimentos', 'perfil_utilizacao', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedimentos', 'perfil_utilizacao')
    # ### end Alembic commands ###
